#!/usr/bin/env node
'use strict'

const fs = require('fs')
const path = require('path')
const http = require('http')
const https = require('https')
const twitter = require('twitter-text')

const reset  = '\x1b[0m'
const red    = '\x1b[31m'
const green  = '\x1b[32m'
const yellow = '\x1b[33m'

fs.readFile(path.resolve(__dirname, 'src', 'main.md'), (err, data) => {
  if (err) { throw err }
  twitter.extractUrls(data.toString(), /https?/).map(url => {
    const scheme = url.startsWith('https:') ? https : http
    scheme.get(url, res => {
      const stat = res.statusCode

      let c
      if      (  0 <= stat && stat < 100) { c = red }
      else if (100 <= stat && stat < 200) { c = yellow }
      else if (200 <= stat && stat < 300) { c = green }
      else if (300 <= stat && stat < 400) { c = yellow }
      else if (400 <= stat && stat < 600) { c = red }
      else { c = red }

      console.log(`${c}${stat}   - ${url} (${res.statusMessage})${reset}`)
    }).on('error', e => {
      console.log(`${red}ERROR - ${url} (${e})${reset}`)
    })
  })
})
